### ISSUE TITLE
Create Models In SQLAlchemy

### ISSUE THREAD

**Issue by thealphadollar** [iit-technology-ambit/common-backend#17]
As per the DB Schema (present in dropbox paper), we should make SQLAlchemy models.

The following guidelines to be followed:

- The current schema will be barebone and we will need to update them with constraints.
- Each model should be placed appropriately in the right file and module.

cc/ @mukul-mehta @grapheo12 Please coordinate on this :small_airplane: 

NOTE: Use proper docstrings with each class and method you write.

**Comment by thealphadollar** [comment]
Please take your time, learn about SQLAlchemy and use best practices while making the models.

**Comment by grapheo12** [comment]
@mukul-mehta Since we're using getters and setters for validation checks. Lets follow the `synonym` method described in this [link](https://gist.github.com/luhn/4170996). 
Actually, while using setters I found that setter name and actual attribute (preferably private) must be different otherwise program runs in infinite loop. 
Please comment on what you think.

**Comment by thealphadollar** [comment]
This looks cool.

**Comment by thealphadollar** [comment]
Closing this since we have implemented.
